name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os:
        #- ubuntu-latest
        - ubuntu-20.04
        - macos-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: make pynauty
    - name: Test
      run: |
        make minimal-test
        make tests
