name: Build in Cygwin
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cygwin setup
        uses: egor-tensin/setup-cygwin@v3
        with:
          packages: python3,make,gcc
      - name: install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U wheel
      - name: install pynauty
        run: |
          python3 -m pip install -U pynauty
          python3 -c 'import pynauty; print(pynauty.__file__)'
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
