# This workflow will install Python dependencies, run tests variety of Python versions
# see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish pynauty on test.pypi.org

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15     # Catalina
        - macos-11.0      # Big Sur
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make -f Makefile.dist tools
    - name: Build packages
      run: make -f Makefile.dist packages
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: echo "make -f Makefile.dist testupload"

